//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("UserMaster")]
    public class User : BaseModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordKey { get; set; }
        public string ResetKey { get; set; }
        public string EmailId { get; set; }
        public long? RefId { get; set; }
        public string UserType { get; set; }
        public int? SelectedCompany { get; set; }

        //Foreign Key
        [ForeignKey("Role")]
        [Column("RoleId")]
        public int RoleId { get; set; }
        [ForeignKey("Company")]
        [Column("CompanyId")]
        public int CompanyId { get; set; }
        
        //Virtual Properties
        public virtual Role Role { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
        public virtual ICollection<UserMenuMapping> UserMenuMapping { get; set; }
    }
}
